const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const api=async(path,opts)=>{const r=await fetch(path,opts);const d=await r.json();if(!r.ok)throw new Error(d.error||`${r.status}`);return d};
const titleMap={command:'Command Center',runs:'Run Ledger',plans:'Plan History',capabilities:'Capability Registry',learning:'Learning Intelligence',evidence:'Evidence Ledger',verifier:'Verifier Center',policies:'Policy Gates',runtime:'Runtime Health',settings:'Governance Settings'};
function kv(label,value,cls=''){return `<div class="data-row"><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b></div>`}
async function loadHealth(){try{const d=await api('/api/health');$('#health').textContent=d.status==='ok'?'RUNTIME HEALTHY':'RUNTIME DEGRADED';$('#capCount').textContent=d.capabilities}catch{$('#health').textContent='RUNTIME UNKNOWN'}}
async function loadRuntimeSummary(){try{const d=await api('/api/runtime');const s=d.sandbox;$('#runtimeSummary').innerHTML=[['GitHub connector',d.connectors.includes('github')?'AVAILABLE':'UNAVAILABLE',d.connectors.includes('github')?'ok':'warn'],['Isolated runner',s.status,s.status==='AVAILABLE'?'ok':'warn'],['Network default',d.network_default,d.network_default==='DENY'?'ok':'warn'],['State persistence',d.state_persistence,d.state_persistence.includes('PERSISTENT')?'ok':'warn'],['Production mutation',d.production_mutation,'warn']].map(x=>`<div><span>${esc(x[0])}</span><b class="${x[2]}">${esc(x[1])}</b></div>`).join('')}catch{$('#runtimeSummary').innerHTML='<div><span>Runtime status</span><b class="warn">UNKNOWN</b></div>'}}
function render(plan){$('#planStatus').textContent=plan.status;$('#planStatus').className='badge '+(plan.status==='VERIFIED_PLAN'?'verified':'blocked');$('#selectedCount').textContent=plan.selections.length;$('#stageCount').textContent=plan.stages.length;$('#blockerCount').textContent=plan.blockers.length;$('#dag').className='dag';$('#dag').innerHTML=plan.stages.map((stage,i)=>`<div class="stage"><span class="stage-index">S${i+1}</span>${stage.map(id=>`<div class="node-card"><b>${esc(id)}</b><small>${i===plan.stages.length-1?'verification / evidence':'governed worker'}</small></div>`).join('')}</div>`).join('');$('#gates').innerHTML=plan.authority_gates.map(g=>`<div class="gate"><b>${esc(g.capability_id)}</b><em class="${g.decision==='ALLOW'?'allow':g.decision==='APPROVAL_REQUIRED'?'approval':'block'}">${esc(g.decision)}</em><small>${esc(g.authority)} · ${esc(g.reason)}</small></div>`).join('')||'<div class="muted">No gates.</div>';const events=[['Intent compiled',plan.intents.join(', ')],['Capabilities routed',`${plan.selections.length} workers + ${plan.io_capabilities.length} I/O bindings`],['DAG composed',`${plan.stages.length} execution stages`],['Policy evaluated',`${plan.authority_gates.length} authority decisions`],['Independent plan verification',plan.status]];$('#timeline').innerHTML=events.map(e=>`<div class="timeline-row"><span class="node"></span><div><b>${esc(e[0])}</b><small>${esc(e[1])}</small></div></div>`).join('')}
async function compilePlan(){const b=$('#planBtn');b.disabled=true;b.textContent='COMPILING…';try{const d=await api('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:$('#goal').value,mode:$('#mode').value})});render(d)}catch(e){$('#planStatus').textContent='BLOCKED';$('#planStatus').className='badge blocked';$('#gates').innerHTML=`<div class="gate"><b>Planner error</b><em class="block">BLOCK</em><small>${esc(e.message)}</small></div>`}finally{b.disabled=false;b.textContent='COMPILE PLAN'}}
async function loadRuns(target='#runsContent'){const rows=await api('/api/runs');$(target).innerHTML=rows.length?rows.map(r=>`<article class="record"><div><b>${esc(r.run_id)}</b><small>${esc(r.timestamp)}</small></div><span class="badge ${r.metadata?.plan_status==='VERIFIED_PLAN'?'verified':'unknown'}">${esc(r.metadata?.plan_status||r.status)}</span><p>${esc(r.metadata?.goal||'No goal captured')}</p><small>${esc(r.metadata?.mode||'—')} · ${esc(r.plan_id)}</small></article>`).join(''):'<div class="empty-state">No runs yet. Compile a plan first.</div>'}
async function loadCapabilities(){const rows=await api('/api/capabilities');$('#capabilitiesContent').innerHTML=rows.map(c=>`<article class="cap-card"><div class="cap-top"><b>${esc(c.id)}</b><span>${esc(c.kind)}</span></div><p>${esc(c.description)}</p><div class="chips"><i>${esc(c.authority)}</i>${c.requires_tools.map(x=>`<i>${esc(x)}</i>`).join('')}${c.requires_connectors.map(x=>`<i>${esc(x)}</i>`).join('')}</div><small>risk ${Number(c.risk).toFixed(2)} · confidence ${Number(c.confidence).toFixed(2)}</small></article>`).join('')}
async function loadLearning(){const d=await api('/api/learning');const entries=Object.entries(d);$('#learningContent').innerHTML=entries.length?entries.map(([id,s])=>`<article class="record"><div><b>${esc(id)}</b><small>${s.samples} samples</small></div><span class="signal">${Number(s.routing_signal).toFixed(3)}</span><p>success ${Number(s.success_rate).toFixed(2)} · unique value ${Number(s.unique_value).toFixed(2)} · false positive ${Number(s.false_positive_rate).toFixed(2)}</p></article>`).join(''):'<div class="empty-state">No feedback samples yet. Learning starts neutral and cannot override authority gates.</div>'}
async function loadEvidence(){const d=await api('/api/evidence');$('#evidenceIntegrity').textContent=d.integrity;$('#evidenceIntegrity').className='badge '+(d.integrity==='VERIFIED'?'verified':'blocked');$('#evidenceContent').innerHTML=d.events.length?d.events.map(e=>`<div class="timeline-row"><span class="node"></span><div><b>${esc(e.kind)} · ${esc(e.subject)}</b><small>${esc(e.timestamp)} · #${e.seq}</small><code>${esc(e.event_hash.slice(0,20))}…</code></div></div>`).join(''):'<div class="empty-state">No runtime evidence yet.</div>'}
async function loadVerifier(){const d=await api('/api/verifier');$('#verifierContent').innerHTML=kv('Independent verifier',d.independent_verifier,'ok')+kv('Receipt equals verification',String(d.receipt_is_verification),d.receipt_is_verification?'warn':'ok')+kv('Verified plans',d.verified_plans,'ok')+kv('Blocked plans',d.blocked_plans,d.blocked_plans?'warn':'')+(d.last_plan?`<article class="record wide"><b>Latest plan</b><p>${esc(d.last_plan.metadata?.goal||'—')}</p><small>${esc(d.last_plan.metadata?.plan_status||'UNKNOWN')}</small></article>`:'')}
async function loadPolicies(){const d=await api('/api/policies');$('#policiesContent').innerHTML=`<div class="invariant-grid">${d.invariants.map(x=>`<div class="invariant">${esc(x)}</div>`).join('')}</div><h3>Authority matrix</h3><div class="data-grid">${Object.entries(d.authority).map(([k,v])=>kv(k,v,k==='READ'?'ok':k==='COMPUTE'?'ok':'warn')).join('')}</div><h3>Network</h3><div class="data-grid">${kv('Default',d.network.default,'ok')}${kv('Selective egress',d.network.selective_egress,'warn')}</div>`}
async function loadRuntime(){const d=await api('/api/runtime');$('#runtimeContent').innerHTML=kv('Tools',d.tools.join(', '))+kv('Connectors',d.connectors.join(', '))+kv('Standing grants',d.standing_grants.join(', ')||'NONE','ok')+kv('Network default',d.network_default,'ok')+kv('Sandbox',d.sandbox.status,d.sandbox.status==='AVAILABLE'?'ok':'warn')+kv('Sandbox backend',d.sandbox.backend||'NOT PRESENT')+kv('Egress allowlist',d.sandbox.egress_allowlist,'warn')+kv('State persistence',d.state_persistence,d.state_persistence.includes('PERSISTENT')?'ok':'warn')+kv('Production mutation',d.production_mutation,'warn')}
async function loadSettings(){const [h,r]=await Promise.all([api('/api/health'),api('/api/runtime')]);$('#settingsContent').innerHTML=kv('Version',h.version)+kv('Trust model',h.trust_model,'ok')+kv('Default orchestration mode','ALL')+kv('Network policy',r.network_default,'ok')+kv('Production writes',r.production_mutation,'warn')+kv('State model',r.state_persistence,r.state_persistence.includes('PERSISTENT')?'ok':'warn')+`<article class="record wide"><b>Governance note</b><p>Settings shown here are effective runtime truth. Mutating authority or production policy is intentionally not exposed as an unauthenticated browser toggle.</p></article>`}
const loaders={runs:()=>loadRuns('#runsContent'),plans:()=>loadRuns('#plansContent'),capabilities:loadCapabilities,learning:loadLearning,evidence:loadEvidence,verifier:loadVerifier,policies:loadPolicies,runtime:loadRuntime,settings:loadSettings};
async function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=titleMap[name]||name;if(loaders[name]){try{await loaders[name]()}catch(e){const target=$(`#view-${name} .page-card`);if(target)target.insertAdjacentHTML('beforeend',`<div class="error-box">${esc(e.message)}</div>`)}}}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view)});$('#planBtn').addEventListener('click',compilePlan);document.addEventListener('click',e=>{const b=e.target.closest('[data-refresh]');if(b&&loaders[b.dataset.refresh])loaders[b.dataset.refresh]()});
loadHealth();loadRuntimeSummary();
